# This file was generated by GoReleaser. DO NOT EDIT.
cask "termp" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a600af83c35576fd4bf9e71fed438e4cc2d48879447c88e95d9b1d5f222267ed"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c2f0f0e75c64269997a1217896001d530ad88f7f9502c27b580b18883bc477c"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3367111da2bdafdfa54dcc46d7ad09debc82f985fe5871b922058816b1c2dbb"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c571e894c69dc9483c25b43e6707a1d6e8c85ef1adfe2be953f3b632dc7cea6"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termp"
  desc "Discord Rich Presence daemon for terminal tools."
  homepage "https://github.com/polter-dev/discord_terminal_presence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `termp setup`; Discord stays blank until you do.
  EOS
end
