# This file was generated by GoReleaser. DO NOT EDIT.
cask "termp" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "b6e500e9626a5c85249561cd8368779b78757836bd28b37446588b83862fd41d"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1520415b71bef27d5bcfc1d6e9f890a481b4c5ebe589bb73114970f3df889b26"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76d14040e19a01c9e721ac60082a611d5a0d54f57605b633274aa0170b7fc2f8"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee79914e681b9e66c3d39d0f4dd0a0876872ff283252698c54be87d5d060e43f"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termp"
  desc "Discord Rich Presence daemon for terminal tools."
  homepage "https://github.com/polter-dev/discord_terminal_presence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    +------------------------------------------------------------------------------+
    |                                                                              |
    |   TERMP SETUP                                                                |
    |                                                                              |
    |   AFTER HOMEBREW FINISHES, RUN:                                              |
    |                                                                              |
    |                            >>>  termp setup  <<<                             |
    |                                                                              |
    |   Discord stays blank until you do.                                          |
    |                                                                              |
    +------------------------------------------------------------------------------+
  EOS
end
