# This file was generated by GoReleaser. DO NOT EDIT.
cask "termp" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "f38c3d09fe15d6716c4ea79599dd7da9f7683f45b3cf575eda295131360909d6"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc8b6519ea7b2bc8c5eb13b209e7eaef4dc2236df63f062043b319a762150002"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab95d2a2c39146b63624963a4879d3a71ca0e611221e5dd4e2d038d8d041b443"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2ba6ecfd7d0ab653161c9f2830de33ac10d855152aca45427743e2c9af701c0"
      url "https://github.com/polter-dev/discord_terminal_presence/releases/download/v#{version}/termp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termp"
  desc "Discord Rich Presence daemon for terminal tools."
  homepage "https://github.com/polter-dev/discord_terminal_presence"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termp"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    +------------------------------------------------------------------------------+
    |                                                                              |
    |   TERMP SETUP                                                                |
    |                                                                              |
    |   AFTER HOMEBREW FINISHES, RUN:                                              |
    |                                                                              |
    |                            >>>  termp setup  <<<                             |
    |                                                                              |
    |   Discord stays blank until you do.                                          |
    |                                                                              |
    +------------------------------------------------------------------------------+
  EOS
end
